export const VIDEO_LIST_REQUEST = 'VIDEO_LIST_REQUEST';
export const VIDEO_LIST_SUCCESS = 'VIDEO_LIST_SUCCESS';
export const VIDEO_LIST_FAIL = 'VIDEO_LIST_FAIL';

export const VIDEO_DETAILS_REQUEST = 'VIDEO_DETAILS_REQUEST';
export const VIDEO_DETAILS_SUCCESS = 'VIDEO_DETAILS_SUCCESS';
export const VIDEO_DETAILS_FAIL = 'VIDEO_DETAILS_FAIL';
