module.exports = {
  mongoURI: process.env.MONGODB_URI,
  mongoDbName: process.env.MONGO_DB_NAME,
  mongoUserCollection: process.env.MONGO_USER_COLLECTION,
  googleRickjwApiKey: process.env.GOOGLE_RICKJW_API_KEY,
  googleClientSecret: process.env.GOOGLE_OAUTH_CLIENT_SECRET,
  googleClientID: process.env.GOOGLE_OAUTH_CLIENT_ID,
  googleServerApiKey: process.env.GOOGLE_SERVER_API_KEY,
  youtubeApiKey: process.env.YOUTUBE_API_KEY,
  fackbookClientID: process.env.FACEBOOK_APP_ID,
  facebookClientSecret: process.env.FACEBOOK_APP_SECRET,
  facebookCallbackUrl: process.env.FACEBOOK_APP_CALLBACK_URL,
  githubClientID: process.env.GITHUB_CLIENT_ID,
  githubClientSecret: process.env.GITHUB_CLIENT_SECRET,
  githubCallbackUrl: process.env.GITHUB_APP_CALLBACK_URL,
  jwtClientSecret: process.env.JWT_SECRET,
  mapQuestKey: process.env.MAPQUEST_KEY,
  mapQuestSecret: process.env.MAPQUEST_SECRET,
  geoCoderProvider: process.env.GEO_CODER_PROVIDER,
  emailUser: process.env.EMAIL_USER,
  emailPwd: process.env.EMAIL_PWD,
  emailProvider: process.env.EMAIL_PROVIDER,
  appName: process.env.APP_NAME,
  serverName: process.env.SERVER_NAME,
  DB_URI: `${process.env.MONGODB_URI}`,
  DB_COL: process.env.MONGO_COLLECTION,
  DB_NAME: process.env.MONGO_DB_NAME,
  DB_USER: process.env.MONGO_DB_USER_LTD,
  DB_USER_PWD: process.env.MONGO_DB_USER_LTD_PWD,
};


